var musiciansList = [
  {name: 'OutKast', venues: ['Coachella']},
  {name: 'Muse', venues: ['Coachella']},
  {name: 'Beck', venues: ['Coachella']},
  {name: 'Skrillex', venues: ['Coachella', 'Bonnaroo']},
  {name: 'Lorde', venues: ['Coachella']},
  {name: 'The Knife', venues: ['Coachella']},
  {name: 'The Replacements', venues: ['Coachella']},
  {name: 'Broken Bells', venues: ['Coachella']},
  {name: 'Zedd', venues: ['Coachella', 'Bonnaroo', 'Ultra']},
  {name: 'Girl Talk', venues: ['Coachella']},
  {name: 'Ellie Goulding', venues: ['Coachella']},
  {name: 'Chromeo', venues: ['Coachella']},
  {name: 'HAIM', venues: ['Coachella']},
  {name: 'Neko Case', venues: ['Coachella']},
  {name: 'AFI', venues: ['Coachella']},
  {name: 'Martin Garrix', venues: ['Coachella']},
  {name: 'Bonobo', venues: ['Coachella']},
  {name: 'Bryan Ferry', venues: ['Coachella']},
  {name: 'The Glitch Mob', venues: ['Coachella', 'Bonnaroo', 'Ultra']},
  {name: 'The Afghan Whigs', venues: ['Coachella']},
  {name: 'Queens of the Stone Age', venues: ['Coachella']},
  {name: 'Pharrell Williams', venues: ['Coachella']},
  {name: 'Foster the People', venues: ['Coachella']},
  {name: 'Pet Shop Boys', venues: ['Coachella']},
  {name: 'MGMT', venues: ['Coachella', 'Ultra']},
  {name: 'Empire of the Sun', venues: ['Coachella', 'Ultra']},
  {name: 'Fatboy Slim', venues: ['Coachella']},
  {name: 'Nas', venues: ['Coachella']},
  {name: 'Kid Cudi', venues: ['Coachella']},
  {name: 'The Head and the Heart', venues: ['Coachella']},
  {name: 'Sleigh Bells', venues: ['Coachella']},
  {name: 'Arcade Fire', venues: ['Coachella']},
  {name: 'Calvin Harris', venues: ['Coachella']},
  {name: 'Neutral Milk Hotel', venues: ['Coachella', 'Bonnaroo']},
  {name: 'Disclosure', venues: ['Coachella', 'Bonnaroo']},
  {name: 'Lana Del Ray', venues: ['Coachella']},
  {name: 'Motorhead', venues: ['Coachella']},
  {name: 'Alesso', venues: ['Coachella']},
  {name: 'Duck Sauce', venues: ['Coachella']},
  {name: 'Little Dragon', venues: ['Coachella']},
  {name: 'Flosstradmus', venues: ['Coachella']},
  {name: 'The Toy Dolls', venues: ['Coachella']},
  {name: 'Adventure Club', venues: ['Coachella']},
  {name: "Elton John", venues: ['Bonnaroo']},
  {name: "Kanye West", venues: ['Bonnaroo']},
  {name: "Jack White", venues: ['Bonnaroo']},
  {name: "Lionel Richie", venues: ['Bonnaroo']},
  {name: "Vampire Weekend", venues: ['Bonnaroo']},
  {name: "The Avett Brothers", venues: ['Bonnaroo']},
  {name: "Arctic Monkeys", venues: ['Bonnaroo']},
  {name: "Frank Ocean", venues: ['Bonnaroo']},
  {name: "The Flaming Lips", venues: ['Bonnaroo']},
  {name: "Nick Cave & The Bad Seeds", venues: ['Bonnaroo']},
  {name: "Kaskade", venues: ['Bonnaroo', 'Ultra']},
  {name: "Wiz Khalifa", venues: ['Bonnaroo']},
  {name: "Damon Albarn", venues: ['Bonnaroo']},
  {name: "Cut Copy The Head and the Heart", venues: ['Bonnaroo']},
  {name: "Ms. Lauryn Hill", venues: ['Bonnaroo']},
  {name: "Funkiest Dancer", venues: ['Bonnaroo']},
  {name: "Chromeo", venues: ['Bonnaroo']},
  {name: "Broken Bells Tedeschi Trucks Band", venues: ['Bonnaroo']},
  {name: "James Blake", venues: ['Bonnaroo']},
  {name: "Bobby Womack", venues: ['Bonnaroo']},
  {name: "Umphrey's McGee", venues: ['Bonnaroo']},
  {name: "Ice Cube", venues: ['Bonnaroo']},
  {name: "Ben Howard Slightly Stoopid", venues: ['Bonnaroo']},
  {name: "Fitz & The Tantrums", venues: ['Bonnaroo']},
  {name: "Cake", venues: ['Bonnaroo']},
  {name: "Janelle Monáe", venues: ['Bonnaroo']},
  {name: "Grouplove", venues: ['Bonnaroo']},
  {name: "Amos Lee", venues: ['Bonnaroo']},
  {name: "CHVRCHES Cage the Elephant", venues: ['Bonnaroo']},
  {name: "Die Antwoord", venues: ['Bonnaroo']},
  {name: "Drive-By Truckers", venues: ['Bonnaroo']},
  {name: "Andrew Bird & the Hands of Glory", venues: ['Bonnaroo']},
  {name: "Mastodon Capital Cities", venues: ['Bonnaroo']},
  {name: "Jake Bugg", venues: ['Bonnaroo']},
  {name: "Chance The Rapper", venues: ['Bonnaroo']},
  {name: "Dr. Dog", venues: ['Bonnaroo']},
  {name: "Yonder Mountain String Band John Butler Trio", venues: ['Bonnaroo']},
  {name: "Little Dragon", venues: ['Bonnaroo']},
  {name: "City and Colour", venues: ['Bonnaroo']},
  {name: "The Naked and Famous Taran Killam", venues: ['Bonnaroo']},
  {name: "Phosphorescent", venues: ['Bonnaroo']},
  {name: "Washed Out", venues: ['Bonnaroo']},
  {name: "Danny Brown", venues: ['Bonnaroo']},
  {name: "Warpaint", venues: ['Bonnaroo']},
  {name: "Sam Smith", venues: ['Bonnaroo']},
  {name: "A$AP Ferg", venues: ['Bonnaroo']},
  {name: "Darkside Seasick Steve", venues: ['Bonnaroo']},
  {name: "Shovels & Rope", venues: ['Bonnaroo']},
  {name: "Lucero", venues: ['Bonnaroo']},
  {name: "Real Estate", venues: ['Bonnaroo']},
  {name: "Carolina Chocolate Drops", venues: ['Bonnaroo']},
  {name: "The Wood Brothers", venues: ['Bonnaroo']},
  {name: "Meshuggah", venues: ['Bonnaroo']},
  {name: "Poliça", venues: ['Bonnaroo']},
  {name: "DakhaBrakha", venues: ['Bonnaroo']},
  {name: "Goat", venues: ['Bonnaroo']},
  {name: "ZZ Ward", venues: ['Bonnaroo']},
  {name: "Seun Kuti & Egypt 80", venues: ['Bonnaroo']},
  {name: "Blackberry Smoke MS MR", venues: ['Bonnaroo']},
  {name: "Hannibal Buress", venues: ['Bonnaroo']},
  {name: "First Aid Kit", venues: ['Bonnaroo']},
  {name: "Rudimental", venues: ['Bonnaroo']},
  {name: "A Tribe Called Red", venues: ['Bonnaroo']},
  {name: "Omar Souleyman The Bouncing Souls", venues: ['Bonnaroo']},
  {name: "Greensky Bluegrass", venues: ['Bonnaroo']},
  {name: "Ty Segall", venues: ['Bonnaroo']},
  {name: "Sarah Jarosz", venues: ['Bonnaroo']},
  {name: "Vintage Trouble", venues: ['Bonnaroo']},
  {name: "Okkervil River White Denim", venues: ['Bonnaroo']},
  {name: "Jonathan Wilson", venues: ['Bonnaroo']},
  {name: "J. Roddy Walston & the Business", venues: ['Bonnaroo']},
  {name: "Robert Delong", venues: ['Bonnaroo']},
  {name: "Cloud Nothings Typhoon", venues: ['Bonnaroo']},
  {name: "Thao & the Get Down Stay Down", venues: ['Bonnaroo']},
  {name: "Valerie June", venues: ['Bonnaroo']},
  {name: "King Khan & the Shrines", venues: ['Bonnaroo']},
  {name: "Cherub", venues: ['Bonnaroo']},
  {name: "BANKS Break Science", venues: ['Bonnaroo']},
  {name: "The Black Lillies", venues: ['Bonnaroo']},
  {name: "The Lone Bellow", venues: ['Bonnaroo']},
  {name: "Caveman", venues: ['Bonnaroo']},
  {name: "Big Sam's Funky Nation Jon Batiste and Stay Human", venues: ['Bonnaroo']},
  {name: "La Santa Cecilia", venues: ['Bonnaroo']},
  {name: "Classixx", venues: ['Bonnaroo']},
  {name: "Allah-Las", venues: ['Bonnaroo']},
  {name: "Cass McCombs", venues: ['Bonnaroo']},
  {name: "Vance Joy", venues: ['Bonnaroo']},
  {name: "Haerts Those Darlins", venues: ['Bonnaroo']},
  {name: "Deafheaven", venues: ['Bonnaroo']},
  {name: "Lake Street Dive", venues: ['Bonnaroo']},
  {name: "St. Paul & The Broken Bones", venues: ['Bonnaroo']},
  {name: "The Wild Feathers The Preatures", venues: ['Bonnaroo']},
  {name: "Blank Range", venues: ['Bonnaroo']},
  {name: "2 Chainz ", venues: ['SXSW']},
  {name: "3LAU", venues: ['SXSW']},
  {name: "A Tribe Called Red", venues: ['SXSW']},
  {name: "ASAP Mob ", venues: ['SXSW']},
  {name: "ASTR", venues: ['SXSW']},
  {name: "Ab-Soul", venues: ['SXSW']},
  {name: "Action Bronson", venues: ['SXSW']},
  {name: "Against Me!", venues: ['SXSW']},
  {name: "Ages and Ages", venues: ['SXSW']},
  {name: "Albert Hammond Jr. ", venues: ['SXSW']},
  {name: "Allen Stone", venues: ['SXSW']},
  {name: "Aloe Blacc", venues: ['SXSW']},
  {name: "Alpha Rev", venues: ['SXSW']},
  {name: "Alvin Risk", venues: ['SXSW']},
  {name: "Ana Tijoux", venues: ['SXSW']},
  {name: "Anamanaguchi", venues: ['SXSW']},
  {name: "Angel Olsen", venues: ['SXSW']},
  {name: "Annie Mac", venues: ['SXSW']},
  {name: "Archie Powell & The Exports", venues: ['SXSW']},
  {name: "Arkells", venues: ['SXSW']},
  {name: "Arthur Beatrice", venues: ['SXSW']},
  {name: "Asher Roth", venues: ['SXSW']},
  {name: "Ava Luna", venues: ['SXSW']},
  {name: "Avi Buffalo", venues: ['SXSW']},
  {name: "BANKS ", venues: ['SXSW']},
  {name: "Badbadnotgood", venues: ['SXSW']},
  {name: "Band of Skulls", venues: ['SXSW']},
  {name: "Basia Bulat", venues: ['SXSW']},
  {name: "Bear Hands", venues: ['SXSW']},
  {name: "Beat Culture", venues: ['SXSW']},
  {name: "bEEdEEgEE", venues: ['SXSW']},
  {name: "Benjamin Booker", venues: ['SXSW']},
  {name: "Betty Who", venues: ['SXSW']},
  {name: "Big Freedia", venues: ['SXSW']},
  {name: "Bishop Nehru", venues: ['SXSW']},
  {name: "Black Cobain", venues: ['SXSW']},
  {name: "Black Lips", venues: ['SXSW']},
  {name: "Black Milk", venues: ['SXSW']},
  {name: "Black Taxi", venues: ['SXSW']},
  {name: "Black Tusk", venues: ['SXSW']},
  {name: "Bleachers", venues: ['SXSW']},
  {name: "Blondfire", venues: ['SXSW']},
  {name: "Blondie ", venues: ['SXSW']},
  {name: "Blouse", venues: ['SXSW']},
  {name: "Bo Ningen", venues: ['SXSW']},
  {name: "Bob Mould", venues: ['SXSW']},
  {name: "Bobby Bare, Jr.", venues: ['SXSW']},
  {name: "Boy and Bear", venues: ['SXSW']},
  {name: "Boyfrndz", venues: ['SXSW']},
  {name: "Boys Noize", venues: ['SXSW']},
  {name: "Brazos", venues: ['SXSW']},
  {name: "Breton", venues: ['SXSW']},
  {name: "Brick + Mortar", venues: ['SXSW']},
  {name: "Bring Me the Horizon", venues: ['SXSW']},
  {name: "Broken Bells", venues: ['SXSW']},
  {name: "Logical", venues: ['SXSW']},
  {name: "Calvin Love", venues: ['SXSW']},
  {name: "Capsula", venues: ['SXSW']},
  {name: "Cashmere Cat", venues: ['SXSW']},
  {name: "Cate Le Bon", venues: ['SXSW']},
  {name: "Cerebral Ballzy", venues: ['SXSW']},
  {name: "Chance the Rapper", venues: ['SXSW']},
  {name: "Charli XCX", venues: ['SXSW']},
  {name: "Cherub", venues: ['SXSW']},
  {name: "Chet Faker", venues: ['SXSW']},
  {name: "Childish Gambino", venues: ['SXSW']},
  {name: "Chlöe Howl", venues: ['SXSW']},
  {name: "Chrissy Murderbot", venues: ['SXSW']},
  {name: "Christopher Owens", venues: ['SXSW']},
  {name: "Chromeo", venues: ['SXSW']},
  {name: "Chuck Inglish", venues: ['SXSW']},
  {name: "Classixx", venues: ['SXSW']},
  {name: "Cloud Nothings ", venues: ['SXSW']},
  {name: "Cody ChesnuTT", venues: ['SXSW']},
  {name: "Coldplay", venues: ['SXSW']},
  {name: "Colourmusic", venues: ['SXSW']},
  {name: "Communist Daughter", venues: ['SXSW']},
  {name: "Connan Mockasin", venues: ['SXSW']},
  {name: "Conner Youngblood", venues: ['SXSW']},
  {name: "Creepoid", venues: ['SXSW']},
  {name: "Curren$y", venues: ['SXSW']},
  {name: "Cymbals", venues: ['SXSW']},
  {name: "Cyril Hahn", venues: ['SXSW']},
  {name: "DZ Deathrays", venues: ['SXSW']},
  {name: "DZ Deathrays", venues: ['SXSW']},
  {name: "Dam-Funk", venues: ['SXSW']},
  {name: "Damon Albarn", venues: ['SXSW']},
  {name: "Dana Falconberry", venues: ['SXSW']},
  {name: "Dave Alvin", venues: ['SXSW']},
  {name: "Deap Vally", venues: ['SXSW']},
  {name: "Deep Cotton", venues: ['SXSW']},
  {name: "Deleted Scenes", venues: ['SXSW']},
  {name: "Delhi 2 Dublin", venues: ['SXSW']},
  {name: "Deniro Farrar", venues: ['SXSW']},
  {name: "Denzel Curry", venues: ['SXSW']},
  {name: "Diane Birch", venues: ['SXSW']},
  {name: "Diane Coffee", venues: ['SXSW']},
  {name: "Diarrhea Planet", venues: ['SXSW']},
  {name: "Dinosaur Bones", venues: ['SXSW']},
  {name: "Dizzy Wright", venues: ['SXSW']},
  {name: "Dom Kennedy", venues: ['SXSW']},
  {name: "Dosh", venues: ['SXSW']},
  {name: "Drenge", venues: ['SXSW']},
  {name: "Dum Dum Girls", venues: ['SXSW']},
  {name: "Duologue", venues: ['SXSW']},
  {name: "Dylan LeBlanc", venues: ['SXSW']},
  {name: "EMA", venues: ['SXSW']},
  {name: "Eagulls", venues: ['SXSW']},
  {name: "East India Youth", venues: ['SXSW']},
  {name: "Eliza Doolittle", venues: ['SXSW']},
  {name: "Elizabeth & the Catapult", venues: ['SXSW']},
  {name: "Empires", venues: ['SXSW']},
  {name: "Esben and the Witch", venues: ['SXSW']},
  {name: "Evans the Death", venues: ['SXSW']},
  {name: "Ex Hex", venues: ['SXSW']},
  {name: "Ezra Furman", venues: ['SXSW']},
  {name: "Fat Tony", venues: ['SXSW']},
  {name: "Fear of Men", venues: ['SXSW']},
  {name: "Fences", venues: ['SXSW']},
  {name: "Flosstradamus", venues: ['SXSW']},
  {name: "Forst Swords", venues: ['SXSW']},
  {name: "Fort Knox", venues: ['SXSW']},
  {name: "Foster the People", venues: ['SXSW']},
  {name: "Foxboro Hot Tubs ", venues: ['SXSW']},
  {name: "French Horn Rebellion", venues: ['SXSW']},
  {name: "Future", venues: ['SXSW']},
  {name: "Future Islands", venues: ['SXSW']},
  {name: "G Love", venues: ['SXSW']},
  {name: "G-Side", venues: ['SXSW']},
  {name: "Gabby Young and Other Animals", venues: ['SXSW']},
  {name: "Gap Dream", venues: ['SXSW']},
  {name: "Gardens & Villa", venues: ['SXSW']},
  {name: "Garland Jeffreys", venues: ['SXSW']},
  {name: "Gary Numan", venues: ['SXSW']},
  {name: "Gentleman Hall", venues: ['SXSW']},
  {name: "Ghost Beach", venues: ['SXSW']},
  {name: "Grieves", venues: ['SXSW']},
  {name: "Gringo Star", venues: ['SXSW']},
  {name: "Gruff Rhys", venues: ['SXSW']},
  {name: "Gunplay", venues: ['SXSW']},
  {name: "Guy Forsyth", venues: ['SXSW']},
  {name: "Ha Ha Tonka", venues: ['SXSW']},
  {name: "Har Mar Superstar", venues: ['SXSW']},
  {name: "Heavenly Beat", venues: ['SXSW']},
  {name: "Hey Ocean!", venues: ['SXSW']},
  {name: "Hieroglyphics", venues: ['SXSW']},
  {name: "High Highs", venues: ['SXSW']},
  {name: "Hollis Brown", venues: ['SXSW']},
  {name: "Hospital Ships", venues: ['SXSW']},
  {name: "Hospitality", venues: ['SXSW']},
  {name: "Hozier", venues: ['SXSW']},
  {name: "Hundred Waters", venues: ['SXSW']},
  {name: "Hunter Hunted", venues: ['SXSW']},
  {name: "Hurray for the Riff Raff", venues: ['SXSW']},
  {name: "Imagine Dragons", venues: ['SXSW']},
  {name: "In The Valley Below", venues: ['SXSW']},
  {name: "Indian", venues: ['SXSW']},
  {name: "Indian Summer", venues: ['SXSW']},
  {name: "Ingrid Michaelson", venues: ['SXSW']},
  {name: "Isaiah Rashad", venues: ['SXSW']},
  {name: "Ital", venues: ['SXSW']},
  {name: "J. Roddy Walston & The Business", venues: ['SXSW']},
  {name: "Jackson Scott", venues: ['SXSW']},
  {name: "Jacques Green", venues: ['SXSW']},
  {name: "Jacuzzi Boys", venues: ['SXSW']},
  {name: "James Iha", venues: ['SXSW']},
  {name: "Japanther", venues: ['SXSW']},
  {name: "Jenny Hval", venues: ['SXSW']},
  {name: "Jeremiah Jae", venues: ['SXSW']},
  {name: "Jeremy Messersmith", venues: ['SXSW']},
  {name: "Jerome LOL", venues: ['SXSW']},
  {name: "Jesse Malin", venues: ['SXSW']},
  {name: "Jessica Lea Mayfield", venues: ['SXSW']},
  {name: "John Fullbright", venues: ['SXSW']},
  {name: "John Newman", venues: ['SXSW']},
  {name: "Jonathan Toubin", venues: ['SXSW']},
  {name: "Julian Lennon", venues: ['SXSW']},
  {name: "Julio Bashmore", venues: ['SXSW']},
  {name: "Jungle", venues: ['SXSW']},
  {name: "Kate Nash", venues: ['SXSW']},
  {name: "Katie Got Bandz", venues: ['SXSW']},
  {name: "Kelis", venues: ['SXSW']},
  {name: "Kelley Stoltz", venues: ['SXSW']},
  {name: "Kendrick Lamar", venues: ['SXSW']},
  {name: "Kevin Gates", venues: ['SXSW']},
  {name: "Kill the Noise", venues: ['SXSW']},
  {name: "Kindness", venues: ['SXSW']},
  {name: "King Louie", venues: ['SXSW']},
  {name: "Kishi Bashi", venues: ['SXSW']},
  {name: "Kraak & Smack", venues: ['SXSW']},
  {name: "Kurt Vile", venues: ['SXSW']},
  {name: "Kyle Andrews", venues: ['SXSW']},
  {name: "Kylesa", venues: ['SXSW']},
  {name: "Lady Gaga", venues: ['SXSW']},
  {name: "Rumored", venues: ['SXSW']},
  {name: "Le1f", venues: ['SXSW']},
  {name: "League of Extraordinary Gz", venues: ['SXSW']},
  {name: "Lee Bannon", venues: ['SXSW']},
  {name: "Lee Fields & The Expressions", venues: ['SXSW']},
  {name: "Leopold and His Fiction", venues: ['SXSW']},
  {name: "Les Claypool", venues: ['SXSW']},
  {name: "Lily & The Parlour Tricks", venues: ['SXSW']},
  {name: "Little Boots", venues: ['SXSW']},
  {name: "Little Dragon", venues: ['SXSW']},
  {name: "Little Hurricane", venues: ['SXSW']},
  {name: "London Grammar", venues: ['SXSW']},
  {name: "Los Lonely Boys", venues: ['SXSW']},
  {name: "Lost in the Trees", venues: ['SXSW']},
  {name: "Lovelife", venues: ['SXSW']},
  {name: "Low Pros (A-Trak & Lex Luger) feat. Migos, Travi$ Scott, Que & Guests ", venues: ['SXSW']},
  {name: "Lucius", venues: ['SXSW']},
  {name: "Rumored", venues: ['SXSW']},
  {name: "Lunice", venues: ['SXSW']},
  {name: "Lydia Loveless", venues: ['SXSW']},
  {name: "MC Lars", venues: ['SXSW']},
  {name: "MS MR", venues: ['SXSW']},
  {name: "Machinedrum", venues: ['SXSW']},
  {name: "Madlib", venues: ['SXSW']},
  {name: "Man Or Astro-Man?", venues: ['SXSW']},
  {name: "Marijuana Deathsquads", venues: ['SXSW']},
  {name: "Mark Kozelek", venues: ['SXSW']},
  {name: "Mark McGuire", venues: ['SXSW']},
  {name: "Mary Lambert", venues: ['SXSW']},
  {name: "Matisyahu", venues: ['SXSW']},
  {name: "Matrimony", venues: ['SXSW']},
  {name: "Meg Myers", venues: ['SXSW']},
  {name: "Melissa Etheridge", venues: ['SXSW']},
  {name: "Merchandise", venues: ['SXSW']},
  {name: "Miami Horror", venues: ['SXSW']},
  {name: "Migos ", venues: ['SXSW']},
  {name: "Milagres", venues: ['SXSW']},
  {name: "Mimicking Birds", venues: ['SXSW']},
  {name: "Miniature Tigers", venues: ['SXSW']},
  {name: "Mirah", venues: ['SXSW']},
  {name: "Miss May I", venues: ['SXSW']},
  {name: "Mobb Deep", venues: ['SXSW']},
  {name: "Mood Rings", venues: ['SXSW']},
  {name: "Morning Parade", venues: ['SXSW']},
  {name: "Mr. Muthafuckin' eXquire", venues: ['SXSW']},
  {name: "Mujeres", venues: ['SXSW']},
  {name: "Mutual Benefit", venues: ['SXSW']},
  {name: "My Education", venues: ['SXSW']},
  {name: "MØ ", venues: ['SXSW']},
  {name: "NO", venues: ['SXSW']},
  {name: "NONONO", venues: ['SXSW']},
  {name: "Nas ", venues: ['SXSW']},
  {name: "Natural Child", venues: ['SXSW']},
  {name: "Nick Catchdubs", venues: ['SXSW']},
  {name: "Nicole Atkins", venues: ['SXSW']},
  {name: "Nipsey Hussle", venues: ['SXSW']},
  {name: "No", venues: ['SXSW']},
  {name: "No Joy", venues: ['SXSW']},
  {name: "No Malice", venues: ['SXSW']},
  {name: "OBN III's", venues: ['SXSW']},
  {name: "OFF!", venues: ['SXSW']},
  {name: "Oberhofer", venues: ['SXSW']},
  {name: "Of Mice and Men", venues: ['SXSW']},
  {name: "Oh Mercy", venues: ['SXSW']},
  {name: "Outernational", venues: ['SXSW']},
  {name: "PUP", venues: ['SXSW']},
  {name: "Papa", venues: ['SXSW']},
  {name: "Pattern Is Movement", venues: ['SXSW']},
  {name: "Peanut Butter Wolf", venues: ['SXSW']},
  {name: "Peelander-Z", venues: ['SXSW']},
  {name: "People Under the Stairs", venues: ['SXSW']},
  {name: "Perfect Pussy", venues: ['SXSW']},
  {name: "Perfume Genius", venues: ['SXSW']},
  {name: "Phantogram", venues: ['SXSW']},
  {name: "Phox", venues: ['SXSW']},
  {name: "Poliça ", venues: ['SXSW']},
  {name: "Pontiak", venues: ['SXSW']},
  {name: "Poolside", venues: ['SXSW']},
  {name: "Problem", venues: ['SXSW']},
  {name: "Psychic Twin", venues: ['SXSW']},
  {name: "Public Service Broadcasting", venues: ['SXSW']},
  {name: "Pujol", venues: ['SXSW']},
  {name: "Quiet Company", venues: ['SXSW']},
  {name: "RAC", venues: ['SXSW']},
  {name: "Radkey", venues: ['SXSW']},
  {name: "Rathborne", venues: ['SXSW']},
  {name: "Ratking", venues: ['SXSW']},
  {name: "Raw Geronimo", venues: ['SXSW']},
  {name: "Real Estate", venues: ['SXSW']},
  {name: "Real Magic", venues: ['SXSW']},
  {name: "Rich Aucoin", venues: ['SXSW']},
  {name: "Ringo Deathstarr", venues: ['SXSW']},
  {name: "Roadkill Ghost Choir", venues: ['SXSW']},
  {name: "Robert Ellis", venues: ['SXSW']},
  {name: "Rockie Fresh", venues: ['SXSW']},
  {name: "Royal Canoe", venues: ['SXSW']},
  {name: "Royal Teeth", venues: ['SXSW']},
  {name: "Rubblebucket", venues: ['SXSW']},
  {name: "Ruby Jane", venues: ['SXSW']},
  {name: "Rustie", venues: ['SXSW']},
  {name: "Ryan Hemsworth", venues: ['SXSW']},
  {name: "S. Carey", venues: ['SXSW']},
  {name: "SKATERS", venues: ['SXSW']},
  {name: "SKATERS", venues: ['SXSW']},
  {name: "SOHN", venues: ['SXSW']},
  {name: "SZA", venues: ['SXSW']},
  {name: "Sage Francis", venues: ['SXSW']},
  {name: "Saint Pepsi", venues: ['SXSW']},
  {name: "Saint Rich", venues: ['SXSW']},
  {name: "Sam Roberts Band", venues: ['SXSW']},
  {name: "Sam Smith", venues: ['SXSW']},
  {name: "San Fermin", venues: ['SXSW']},
  {name: "Sarah Jaffe", venues: ['SXSW']},
  {name: "Saul Williams", venues: ['SXSW']},
  {name: "ScHoolboy Q", venues: ['SXSW']},
  {name: "Secret Colours", venues: ['SXSW']},
  {name: "Shad", venues: ['SXSW']},
  {name: "Shakey Graves", venues: ['SXSW']},
  {name: "Shawn Chrystopher", venues: ['SXSW']},
  {name: "ShowYouSuck", venues: ['SXSW']},
  {name: "Sister Sparrow & The Dirty Birds", venues: ['SXSW']},
  {name: "Sisu", venues: ['SXSW']},
  {name: "Ski Lodge", venues: ['SXSW']},
  {name: "Skream", venues: ['SXSW']},
  {name: "Slaughterhouse", venues: ['SXSW']},
  {name: "Sleeper Agent", venues: ['SXSW']},
  {name: "Slim Thug", venues: ['SXSW']},
  {name: "Slow Magic", venues: ['SXSW']},
  {name: "Small Black", venues: ['SXSW']},
  {name: "Smoke DZA", venues: ['SXSW']},
  {name: "Social Studies", venues: ['SXSW']},
  {name: "Soft Swells", venues: ['SXSW']},
  {name: "Sophie", venues: ['SXSW']},
  {name: "Soundgarden ", venues: ['SXSW']},
  {name: "Speedy Ortiz", venues: ['SXSW']},
  {name: "Spirit Animal", venues: ['SXSW']},
  {name: "Split Single", venues: ['SXSW']},
  {name: "St. Vincent ", venues: ['SXSW']},
  {name: "Steve Gunn", venues: ['SXSW']},
  {name: "Steve Wynn", venues: ['SXSW']},
  {name: "Supreme Cuts", venues: ['SXSW']},
  {name: "Suzanne Vega", venues: ['SXSW']},
  {name: "Syd Arthur", venues: ['SXSW']},
  {name: "THEESatisfaction", venues: ['SXSW']},
  {name: "Rumored", venues: ['SXSW']},
  {name: "THEESatisfaction", venues: ['SXSW']},
  {name: "Talib Kweli", venues: ['SXSW']},
  {name: "Team Me", venues: ['SXSW']},
  {name: "Team Spirit", venues: ['SXSW']},
  {name: "Tech N9ne", venues: ['SXSW']},
  {name: "Teengirl Fantasy", venues: ['SXSW']},
  {name: "Tennis", venues: ['SXSW']},
  {name: "Tensnake", venues: ['SXSW']},
  {name: "The Apache Relay", venues: ['SXSW']},
  {name: "The Autumn Defense", venues: ['SXSW']},
  {name: "The Baseball Project", venues: ['SXSW']},
  {name: "The Belle Game", venues: ['SXSW']},
  {name: "The Binary Code", venues: ['SXSW']},
  {name: "The Black Lillies", venues: ['SXSW']},
  {name: "The Blank Tapes", venues: ['SXSW']},
  {name: "The Bots", venues: ['SXSW']},
  {name: "The Boxing Lesson", venues: ['SXSW']},
  {name: "The Bright Light Social Hour", venues: ['SXSW']},
  {name: "The Casket Girls", venues: ['SXSW']},
  {name: "The Chevelles", venues: ['SXSW']},
  {name: "The Chris Gethard Show", venues: ['SXSW']},
  {name: "The Colourist", venues: ['SXSW']},
  {name: "The Darcys", venues: ['SXSW']},
  {name: "The Deep Dark Woods", venues: ['SXSW']},
  {name: "The Dunwells", venues: ['SXSW']},
  {name: "The Felice Brothers", venues: ['SXSW']},
  {name: "The Fresh & Onlys", venues: ['SXSW']},
  {name: "The Ghost of a Saber Tooth Tiger", venues: ['SXSW']},
  {name: "The Hood Internet", venues: ['SXSW']},
  {name: "The Knocks", venues: ['SXSW']},
  {name: "The Kooks", venues: ['SXSW']},
  {name: "The Magic Numbers", venues: ['SXSW']},
  {name: "The Mary Onettes", venues: ['SXSW']},
  {name: "The Men", venues: ['SXSW']},
  {name: "The Mowglis", venues: ['SXSW']},
  {name: "The Orwells", venues: ['SXSW']},
  {name: "The Pack A.D.", venues: ['SXSW']},
  {name: "The Pains of Being Pure at Heart", venues: ['SXSW']},
  {name: "The Range", venues: ['SXSW']},
  {name: "The So So Glos", venues: ['SXSW']},
  {name: "The Whigs", venues: ['SXSW']},
  {name: "The Wilderness of Manitoba", venues: ['SXSW']},
  {name: "Those Darlins", venues: ['SXSW']},
  {name: "Thumpers", venues: ['SXSW']},
  {name: "Timber Timbre", venues: ['SXSW']},
  {name: "Tinariwen", venues: ['SXSW']},
  {name: "Tokyo Police Club ", venues: ['SXSW']},
  {name: "Torres", venues: ['SXSW']},
  {name: "Touche Amore", venues: ['SXSW']},
  {name: "Tourist", venues: ['SXSW']},
  {name: "Trae Tha Truth", venues: ['SXSW']},
  {name: "Travi$ Scott", venues: ['SXSW']},
  {name: "Trust", venues: ['SXSW']},
  {name: "Tweens", venues: ['SXSW']},
  {name: "Twin Peaks", venues: ['SXSW']},
  {name: "Ty Dolla $ign", venues: ['SXSW']},
  {name: "Tyler the Creator ", venues: ['SXSW']},
  {name: "Typhoon", venues: ['SXSW']},
  {name: "Tyvek", venues: ['SXSW']},
  {name: "UME", venues: ['SXSW']},
  {name: "Urge Overkill", venues: ['SXSW']},
  {name: "VV Brown", venues: ['SXSW']},
  {name: "Vance Joy", venues: ['SXSW']},
  {name: "Vertical Scratchers", venues: ['SXSW']},
  {name: "Vic Mensa", venues: ['SXSW']},
  {name: "Vince Staples", venues: ['SXSW']},
  {name: "Vockah Redu", venues: ['SXSW']},
  {name: "Wanda Jackson", venues: ['SXSW']},
  {name: "Warm Soda", venues: ['SXSW']},
  {name: "Warpaint", venues: ['SXSW']},
  {name: "Washed Out", venues: ['SXSW']},
  {name: "Waters", venues: ['SXSW']},
  {name: "We Were Promised Jetpacks", venues: ['SXSW']},
  {name: "Weekend", venues: ['SXSW']},
  {name: "Wet", venues: ['SXSW']},
  {name: "Wild Child", venues: ['SXSW']},
  {name: "Wild Cub", venues: ['SXSW']},
  {name: "Wild Moccasins", venues: ['SXSW']},
  {name: "Willie Nelson", venues: ['SXSW']},
  {name: "Wolf Alice", venues: ['SXSW']},
  {name: "Woman's Hour", venues: ['SXSW']},
  {name: "Wye Oak", venues: ['SXSW']},
  {name: "X ", venues: ['SXSW']},
  {name: "YB", venues: ['SXSW']},
  {name: "YG", venues: ['SXSW']},
  {name: "Yamantaka // Sonic Titan", venues: ['SXSW']},
  {name: "Yellow Ostrich", venues: ['SXSW']},
  {name: "Yip Deceiver", venues: ['SXSW']},
  {name: "Young Thug", venues: ['SXSW']},
  {name: "Young the Giant", venues: ['SXSW']},
  {name: "Yvette", venues: ['SXSW']},
  {name: "Zedd", venues: ['SXSW']},
  {name: "Zeds Dead", venues: ['SXSW']},
  {name: "Zeus", venues: ['SXSW']},
  {name: "bEEdEEgEE", venues: ['SXSW']},
  {name: "mr. Gnome", venues: ['SXSW']},
  {name: "together PANGEA", venues: ['SXSW']},
  {name: "OUTKAST", venues: ['Counterpoint']},
  {name: "PRETTY LIGHTS", venues: ['Counterpoint']},
  {name: "FOSTER THE PEOPLE", venues: ['Counterpoint']},
  {name: "STS9", venues: ['Counterpoint']},
  {name: "J. COLE", venues: ['Counterpoint']},
  {name: "MAJOR LAZER", venues: ['Counterpoint']},
  {name: "KREWELLA", venues: ['Counterpoint']},
  {name: "BIG GIGANTIC", venues: ['Counterpoint']},
  {name: "FLUX PAVILION", venues: ['Counterpoint']},
  {name: "ABOVE & BEYOND", venues: ['Counterpoint']},
  {name: "MATT & KIM", venues: ['Counterpoint']},
  {name: "THIEVERY CORPORATION", venues: ['Counterpoint']},
  {name: "A-TRAK", venues: ['Counterpoint']},
  {name: "JANELLE MONAE", venues: ['Counterpoint']},
  {name: "BOYS NOIZE", venues: ['Counterpoint']},
  {name: "WOLFGANG GARTNER", venues: ['Counterpoint']},
  {name: "SLEIGH BELLS", venues: ['Counterpoint']},
  {name: "FLOSSTRADAMUS", venues: ['Counterpoint']},
  {name: "CHANCE THE RAPPER", venues: ['Counterpoint']},
  {name: "GRIZ •SHPONGLE (SIMON POSFORD DJ SET)", venues: ['Counterpoint']},
  {name: "PHANTOGRAM", venues: ['Counterpoint']},
  {name: "MOON TAXI •RUN THE JEWELS (EL-P & KILLER MIKE)", venues: ['Counterpoint']},
  {name: "SCHOOLBOY Q", venues: ['Counterpoint']},
  {name: "MAT ZO", venues: ['Counterpoint']},
  {name: "PAPADOSIO", venues: ['Counterpoint']},
  {name: "RICH HOMIE QUAN", venues: ['Counterpoint']},
  {name: "GTA", venues: ['Counterpoint']},
  {name: "TYCHO", venues: ['Counterpoint']},
  {name: "ST. LUCIA", venues: ['Counterpoint']},
  {name: "THE REVIVALISTS", venues: ['Counterpoint']},
  {name: "YACHT •MINNESOTA", venues: ['Counterpoint']},
  {name: "OTT", venues: ['Counterpoint']},
  {name: "THE POLISH AMBASSADOR", venues: ['Counterpoint']},
  {name: "XXYYXX", venues: ['Counterpoint']},
  {name: "THUNDERCAT", venues: ['Counterpoint']},
  {name: "POOLSIDE", venues: ['Counterpoint']},
  {name: "WILD CUB •KILL PARIS", venues: ['Counterpoint']},
  {name: "CONGOROCK", venues: ['Counterpoint']},
  {name: "CASHMERE CAT", venues: ['Counterpoint']},
  {name: "HUCCI", venues: ['Counterpoint']},
  {name: "RUBBLEBUCKET", venues: ['Counterpoint']},
  {name: "NOSAJ THING •DAN CROLL", venues: ['Counterpoint']},
  {name: "MAYHEM", venues: ['Counterpoint']},
  {name: "GREEN LANTERN", venues: ['Counterpoint']},
  {name: "BUTCH CLANCY", venues: ['Counterpoint']},
  {name: "LANCE HERBSTRONG", venues: ['Counterpoint']},
  {name: "TOURIST •RATKING", venues: ['Counterpoint']},
  {name: "JONAS RATHSMAN", venues: ['Counterpoint']},
  {name: "WATCH THE DUCK", venues: ['Counterpoint']},
  {name: "KAP SLAP", venues: ['Counterpoint']},
  {name: "CHROME SPARKS •BASIC VACATION", venues: ['Counterpoint']},
  {name: "JMSN", venues: ['Counterpoint']},
  {name: "PEGBOARD NERDS", venues: ['Counterpoint']},
  {name: "THE FLOOZIES", venues: ['Counterpoint']},
  {name: "THRIFTWORKS", venues: ['Counterpoint']},
  {name: "DEEP COTTON •FIVE KNIVES", venues: ['Counterpoint']},
  {name: "INFINITY SHRED", venues: ['Counterpoint']},
  {name: "REAL MAGIC", venues: ['Counterpoint']},
  {name: "ROMAN GIANARTHUR", venues: ['Counterpoint']},
  {name: "BAGHEERA", venues: ['Counterpoint']},
  {name: "SKRAUSE •SHREDDIE MERCURY", venues: ['Counterpoint']},
  {name: "MARTINA MCFLYY", venues: ['Counterpoint']},
  {name: "CHRIS BUSHNELL", venues: ['Counterpoint']},
  {name: "BLKKMORRIS", venues: ['Counterpoint']},
  {name: "PANTHER GOD •PLOYD", venues: ['Counterpoint']},
  {name: "THE DIFFERENCE MACHINE", venues: ['Counterpoint']},
];