<?php
$units = array(
	array(
		'Unit' => array(
			'id' => '3',
			'unit_type_id' => '1',
			'name' => 'Parliament',
			'parent_id' => null,
			'lft' => '1',
			'rght' => '6',
			'province_id' => '1',
			'web_address' => 'www.parliament.gov.za',
			'physical_address' => 'Parliament Building, Room V20, Parliament Street, Cape Town',
			'postal_address' => 'Po Box 15, Cape Town, 8000',
			'telephone' => '021 403 2595',
			'fax' => '021 461 9462',
			'email' => 'info@parliament.gov.za',
			'description' => 'The national legislature or Parliament consists of two Houses, the National Assembly and National Council of Provinces, whose members are elected by the people of South Africa. Each House has its own distinct functions and powers, as set out in the Constitution. The National Assembly is responsible for choosing the President, passing laws, ensuring that the members of the executive perform their work properly and providing a forum where the representatives of the people can publicly debate issues. The National Council of Provinces is also involved in the law-making process and provides a forum for debate on issues affecting the provinces. Its main focus is ensuring that provincial interests are taken into account in the national sphere of government. In specific cases, local government representatives also participate in debates in the National Council of Provinces. Parliament plays a direct and active role in national affairs. It is the place where the members of Parliament look after your interests. Members of Parliament (MPs) have many responsibilities, including: making laws that will improve our lives; discussing and debating government policy and other political issues; consulting with you, the people, and representing your views in Parliament; helping people in their constituencies; approving the budgets of government departments, as presented to Parliament by the Minister of Finance; making sure that the work that government promised to do is being done; and checking that public money is being spent wisely.',
			'current_tenders' => '',
			'vacancies' => '',
			'status' => '1',
			'status_reason' => '',
			'newsletter' => '1',
			'person_count' => '13',
			'annual_type_id' => '2',
			'created' => '0000-00-00 00:00:00',
			'modified' => '2015-04-24 14:06:09'
		),
		'UnitType' => array(
			'id' => '1',
			'name' => 'Parliament',
			'menu_name' => 'Parliament',
			'display' => '1',
			'sort_order' => '1',
			'created' => '2015-01-28 10:39:50',
			'modified' => '2015-04-07 12:07:37'
		),
		'children' => array(
			array(
				'Unit' => array(
					'id' => '1',
					'unit_type_id' => '1',
					'name' => 'National Assembly (NA)',
					'parent_id' => '3',
					'lft' => '2',
					'rght' => '3',
					'province_id' => '1',
					'web_address' => 'www.parliament.gov.za',
					'physical_address' => 'Parliament Building, Room E118, Parliament Street, Cape Town',
					'postal_address' => 'PO Box 15, Cape Town, 8000',
					'telephone' => '021 403 2595',
					'fax' => '021 461 9462',
					'email' => 'info@parliament.gov.za',
					'description' => 'The National Assembly (NA) is one of the two Houses of Parliament. The National Assembly is responsible for choosing the President, passing laws, ensuring that the members of the executive perform their work properly and providing a forum where the representatives of the people can publicly debate issues. The Speaker is the head and spokesperson of the National Assembly. The Speaker has many responsibilities which include constitutional, statutory (in terms of the law), procedural and administrative powers and functions. The duties of the Speaker fall broadly into three categories, namely: presiding over sittings of the House, maintaining order and applying its rules; acting as representative and spokesperson for the Assembly and (with the Chairperson of the Council) for Parliament; and acting as chief executive officer for Parliament, in conjunction with the Chairperson of the Council.',
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '406',
					'annual_type_id' => '3',
					'created' => '0000-00-00 00:00:00',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '1',
					'name' => 'Parliament',
					'menu_name' => 'Parliament',
					'display' => '1',
					'sort_order' => '1',
					'created' => '2015-01-28 10:39:50',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			),
			array(
				'Unit' => array(
					'id' => '2',
					'unit_type_id' => '1',
					'name' => 'National Council of Provinces (NCOP)',
					'parent_id' => '3',
					'lft' => '4',
					'rght' => '5',
					'province_id' => '1',
					'web_address' => 'www.parliament.gov.za',
					'physical_address' => 'Parliament Building, Parliament Street, Room S11, Cape Town',
					'postal_address' => 'Po Box 15, Cape Town, 8000',
					'telephone' => '021 403 2110 / 2115 / 3221',
					'fax' => '021 461 9460',
					'email' => 'info@parliament.gov.za',
					'description' => 'The National Council of Provinces (NCOP) is one of the two Houses of Parliament. The NCOP is constitutionally mandated to ensure that provincial interests are taken into account in the national sphere of government. This is done through participation in the national legislative process and by providing a national forum for consideration of issues affecting provinces. The NCOP also plays a unique role in the promotion of the principles of Cooperative Government and Intergovernmental Relations. It ensures that the three spheres of government work together in performing their unique functions in terms of the Constitution and that in doing so, they do not encroach in each others area of competence. This ensures that synergy exists between the spheres on matters of concurrent competence.',
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '61',
					'annual_type_id' => '3',
					'created' => '0000-00-00 00:00:00',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '1',
					'name' => 'Parliament',
					'menu_name' => 'Parliament',
					'display' => '1',
					'sort_order' => '1',
					'created' => '2015-01-28 10:39:50',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			)
		)
	),
	array(
		'Unit' => array(
			'id' => '4',
			'unit_type_id' => '2',
			'name' => 'The Presidency',
			'parent_id' => null,
			'lft' => '7',
			'rght' => '24',
			'province_id' => '1',
			'web_address' => 'www.thepresidency.gov.za',
			'physical_address' => 'Union Buildings, Government Avenue, Pretoria',
			'postal_address' => 'Private Bag X1000, Pretoria, 0001',
			'telephone' => '012 300 5200',
			'fax' => '012 323 8246',
			'email' => 'president@presidency.gov.za',
			'description' => 'The Presidency comprises of four political principals: The President, who is the Head of State and Government, The Deputy President, who is the Leader of Government Business (in Parliament), the Minister of the National Planning Commission and the Minister of Performance, Monitoring and Evaluation as well as Administration. The Presidency has three structures which support governance operations directly: the Cabinet Office; Policy Coordination and Advisory Services (PCAS); and Legal and Executive Services. The Presidencys key role in the executive management and coordination of Government lies in its responsibility to organize governance. In this regard, a key aim is the facilitation of an integrated and coordinated approach to governance. This is being achieved through creative, cross-sectoral thinking on policy issues and the enhancement of the alignment of sectoral priorities with the national strategic policy framework and other Government priorities. The mission of The Presidency is to support the President, the Deputy President and other political principals within The Presidency to execute their responsibilities, as outlined in the Constitution and the programme of government. The Presidencys strategic outcome-orientated goals are to: lead in integrated planning and in the performance monitoring and oversight of government policies and programmes; support the President and Deputy President in exercising their constitutional responsibilities to promote national unity and social cohesion; and assist the President and the Deputy President in advancing the interests of South Africa in the international arena.',
			'current_tenders' => '',
			'vacancies' => '',
			'status' => '1',
			'status_reason' => '',
			'newsletter' => '1',
			'person_count' => '16',
			'annual_type_id' => '1',
			'created' => '0000-00-00 00:00:00',
			'modified' => '2015-04-24 14:06:09'
		),
		'UnitType' => array(
			'id' => '2',
			'name' => 'Presidency',
			'menu_name' => 'Presidency',
			'display' => '1',
			'sort_order' => '2',
			'created' => '2015-01-28 10:39:58',
			'modified' => '2015-04-07 12:07:37'
		),
		'children' => array(
			array(
				'Unit' => array(
					'id' => '29',
					'unit_type_id' => '3',
					'name' => 'Department: Performance Monitoring and Evaluation',
					'parent_id' => '4',
					'lft' => '8',
					'rght' => '9',
					'province_id' => '1',
					'web_address' => 'www.thepresidency-dpme.gov.za',
					'physical_address' => 'The Union Buildings, East Wing, Government Avenue, Pretoria, 0001',
					'postal_address' => 'Private Bag X944, Pretoria, 0001',
					'telephone' => '012 312 0000',
					'fax' => '012 323 8246',
					'email' => '',
					'description' => 'The mission of the Department of Performance Monitoring and Evaluation is to work with partners to improve government performance in achieving desired outcomes and to improve service delivery through changing the way government works. The Department aims to achieve this through coherent priority setting; robust monitoring and evaluation related to the achievement of outcomes, institutional performance monitoring, monitoring of frontline service delivery; and supporting change and transformation through innovative and appropriate solutions and interventions.',
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '16',
					'annual_type_id' => '1',
					'created' => '0000-00-00 00:00:00',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '3',
					'name' => 'National Department',
					'menu_name' => 'National Departments',
					'display' => '1',
					'sort_order' => '4',
					'created' => '2015-01-28 10:40:08',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			),
			array(
				'Unit' => array(
					'id' => '31',
					'unit_type_id' => '3',
					'name' => 'Department: Women',
					'parent_id' => '4',
					'lft' => '20',
					'rght' => '23',
					'province_id' => '1',
					'web_address' => 'www.women.gov.za',
					'physical_address' => '36 Hamilton Street, Arcadia, Pretoria',
					'postal_address' => 'Private Bag X931, Pretoria, 0001',
					'telephone' => '012 359 0000',
					'fax' => '086 683 5502',
					'email' => 'info@women.gov.za',
					'description' => 'The mission of the Department of Women is to accelerate socio-economic transformation and implementation for womes empowerment and participation through oversight, monitoring, evaluation and influencing policy. The priority of the Ministry and the Department will be to ensure that womes socio-economic empowerment and womes rights are mainstreamed across all sectors of society through: monitoring the extent to which social and economic circumstances of women are significantly improved; promoting, advocating for and monitoring womes empowerment and gender equality; promoting the understanding of differential circumstances of women and men in society and the impact of seemingly neutral decisions, plans, laws, policies and practices on either gender through capacity building on gender mainstreaming and responsive gender budgeting; and facilitating and monitoring capacity building and skills development for women to participate meaningfully in all areas of the economy and the workplace.',
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '7',
					'annual_type_id' => '1',
					'created' => '0000-00-00 00:00:00',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '3',
					'name' => 'National Department',
					'menu_name' => 'National Departments',
					'display' => '1',
					'sort_order' => '4',
					'created' => '2015-01-28 10:40:08',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array(
					array(
						'Unit' => array(
							'id' => '52',
							'unit_type_id' => '4',
							'name' => 'Commission for Gender Equality (CGE)',
							'parent_id' => '31',
							'lft' => '21',
							'rght' => '22',
							'province_id' => '1',
							'web_address' => 'www.cge.org.za',
							'physical_address' => 'Old Womes Jail, Constitutional Hill, 2 Kotze Street, Braamfontein, Johannesburg',
							'postal_address' => 'PO Box 32175, Braamfontein, 2017',
							'telephone' => '011 403 7182',
							'fax' => '011 403 7188',
							'email' => 'cgeinfo@cge.org.za',
							'description' => 'The mission of the Commission for Gender Equality (CGE) is to promote respect for gender equality and the protection, development and attainment of gender equality. The CGE shall advance, promote and protect gender equality in South Africa through undertaking research, public education, policy development, legislative initiatives, effective monitoring and litigation. The CGs functions include: monitoring and evaluating the policies and practices of government, the private sector and other organisations to ensure that they promote and protect gender equality; public education and information; reviewing existing and upcoming legislation from a gender perspective investigating inequality; commissioning research and making recommendations to parliament or other authorities; investigating complaints on any gender related issue; and monitoring/reporting on compliance with international conventions.',
							'current_tenders' => '',
							'vacancies' => '',
							'status' => '1',
							'status_reason' => '',
							'newsletter' => '1',
							'person_count' => '12',
							'annual_type_id' => '2',
							'created' => '0000-00-00 00:00:00',
							'modified' => '2015-04-24 14:06:09'
						),
						'UnitType' => array(
							'id' => '4',
							'name' => 'Constitutional Body',
							'menu_name' => 'Constitutional Bodies',
							'display' => '1',
							'sort_order' => '3',
							'created' => '2015-01-28 10:40:17',
							'modified' => '2015-04-07 12:07:37'
						),
						'children' => array()
					)
				)
			),
			array(
				'Unit' => array(
					'id' => '76',
					'unit_type_id' => '6',
					'name' => 'Brand South Africa',
					'parent_id' => '4',
					'lft' => '14',
					'rght' => '15',
					'province_id' => '1',
					'web_address' => 'www.brandsouthafrica.com',
					'physical_address' => '103 Central Street, Houghton, Johannesburg',
					'postal_address' => 'PO Box 87168, Houghton, Gauteng, 2041',
					'telephone' => '011 483 0122',
					'fax' => '011 483 0124',
					'email' => 'info@brandsouthafrica.com',
					'description' => 'The primary objective of Brand South Africa is to develop and implement a proactive marketing and communication strategy for South Africa, and to promote South Africa. Their role is to create a positive, unified image of South Africa; one that builds pride, promotes investment and tourism, and helps new enterprises and job creation. Brand South Africa operates on four platforms: raising awareness internationally of all that South Africa has to offer investors; operating missions abroad promoting investment and export industries; mobilising influential South Africans as well as members of the media abroad; and boosting local pride and patriotism through various campaigns.',
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '38',
					'annual_type_id' => '2',
					'created' => '0000-00-00 00:00:00',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '6',
					'name' => 'Public Entity',
					'menu_name' => 'Public Entities',
					'display' => '1',
					'sort_order' => '6',
					'created' => '2015-01-28 10:40:34',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			),
			array(
				'Unit' => array(
					'id' => '118',
					'unit_type_id' => '6',
					'name' => 'Media Development and Diversity Agency (MDDA)',
					'parent_id' => '4',
					'lft' => '10',
					'rght' => '11',
					'province_id' => '1',
					'web_address' => 'www.mdda.org.za',
					'physical_address' => '31 Princess of Wales Terrace, 4th Floor, Parktown, Johannesburg, 2193',
					'postal_address' => 'PO Box 42846, Fordsburg, 2033',
					'telephone' => '011 643 1100',
					'fax' => '011 643 1129',
					'email' => 'info@mdda.org.za',
					'description' => 'The mission of the Media Development and Diversity Agency (MDDA) is to ensure the sustainable development of vibrant, innovative and people centred media. The Agencs mandate and objectives are to: create an enabling environment for media development and diversity which reflects the needs and aspirations of all South Africans; redress exclusion and marginalisation of disadvantaged communities and persons from access to the media and the media industry; promote media development and diversity by providing support primarily to community and small commercial media projects; encourage ownership and control of, and access to, media by historically disadvantaged communities as well as by historically diminished indigenous language and cultural groups; encourage the development of human resources and training, and capacity building, within the media industry, especially amongst historically disadvantaged groups; encourage the channelling of resources to the community media and small commercial media sectors; raise public awareness with regard to media development and diversity issues and liaise with other statutory bodies such as the Independent Communications Authority of South Africa (ICASA) and the Universal Service and Access Agency (USAASA).',
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '19',
					'annual_type_id' => '2',
					'created' => '0000-00-00 00:00:00',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '6',
					'name' => 'Public Entity',
					'menu_name' => 'Public Entities',
					'display' => '1',
					'sort_order' => '6',
					'created' => '2015-01-28 10:40:34',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			),
			array(
				'Unit' => array(
					'id' => '135',
					'unit_type_id' => '6',
					'name' => 'National House of Traditional Leaders',
					'parent_id' => '4',
					'lft' => '16',
					'rght' => '17',
					'province_id' => '1',
					'web_address' => 'www.nhtl.gov.za',
					'physical_address' => '501 Corner Pretorius And Beatrix Streets, Pencardia 1, Arcadia, Pretoria',
					'postal_address' => 'Private Bag X196, Pretoria, 0001',
					'telephone' => '012 336 5853',
					'fax' => '086 568 0765',
					'email' => '',
					'description' => null,
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '3',
					'annual_type_id' => '3',
					'created' => '0000-00-00 00:00:00',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '6',
					'name' => 'Public Entity',
					'menu_name' => 'Public Entities',
					'display' => '1',
					'sort_order' => '6',
					'created' => '2015-01-28 10:40:34',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			)
		)
	),
	array(
		'Unit' => array(
			'id' => '50',
			'unit_type_id' => '4',
			'name' => 'Auditor-General South Africa (Office of the)',
			'parent_id' => null,
			'lft' => '767',
			'rght' => '768',
			'province_id' => '1',
			'web_address' => 'www.agsa.co.za',
			'physical_address' => '300 Middel Street, New Muckleneuk, Pretoria',
			'postal_address' => 'PO Box 446, Pretoria, 0001',
			'telephone' => '012 426 8000',
			'fax' => '012 426 8257',
			'email' => 'agsa@agsa.co.za',
			'description' => 'The mission of the Auditor-General South Africa (AGSA) is to strengthen our countrs democracy by enabling oversight, accountability and governance in the public sector through auditing, thereby building public confidence. The AGSA not only has to audit and report on the financial management in the public sector, it also has to do so in a manner that will enable the legislature (parliamentarians) to call the executive (cabinet ministers) to account for how they dealt with taxpayers money. AGSs strategic objectives are to: make value-adding recommendations to auditees; maintain excellent quality of auditing; make certain that our messages reach all stakeholders; build a motivated, high-performing and diverse workforce; create access to the relevant skills and knowledge required for our work; adhere to standards of excellence for clean administration; continually improve the timeliness of AGSA reports; maximise AGSs contribution to transformation; execute the organisational mandate economically, efficiently and effectively; ensure sufficient funding for the achievement of the mandate while maintaining our independence; and establish, maintain and own stakeholder relationships to encourage clean administration.',
			'current_tenders' => '',
			'vacancies' => '',
			'status' => '1',
			'status_reason' => '',
			'newsletter' => '1',
			'person_count' => '14',
			'annual_type_id' => '2',
			'created' => '0000-00-00 00:00:00',
			'modified' => '2015-04-24 14:06:09'
		),
		'UnitType' => array(
			'id' => '4',
			'name' => 'Constitutional Body',
			'menu_name' => 'Constitutional Bodies',
			'display' => '1',
			'sort_order' => '3',
			'created' => '2015-01-28 10:40:17',
			'modified' => '2015-04-07 12:07:37'
		),
		'children' => array()
	),
	array(
		'Unit' => array(
			'id' => '53',
			'unit_type_id' => '4',
			'name' => 'Financial and Fiscal Commission',
			'parent_id' => null,
			'lft' => '769',
			'rght' => '770',
			'province_id' => '1',
			'web_address' => 'www.ffc.co.za',
			'physical_address' => '2nd Floor, Montrose Place, Waterfall Park, Bekker Street, Vorna Valley, Midrand',
			'postal_address' => 'Private Bag X69, Halfway House, 1685',
			'telephone' => '011 207 2300',
			'fax' => '011 207 2344',
			'email' => 'info@ffc.co.za',
			'description' => 'The Financial and Fiscal Commission is an independent and impartial advisory institution, which the Government has to consult with regard to the division of revenue among the three spheres of government and in the enactment of legislation pertaining to provincial taxes, municipal fiscal powers and functions, and provincial and municipal loans. The strategic direction of the Commission is reflected in its Corporate Strategic Plan and in the Estimates of National Expenditure. It is informed by, amongst others, the Commissios strategic outcomes-orientated goals of a sustainable and equitable system of intergovernmental fiscal relations (IGFR); a no surprises and future-orientated approach to its endeavours; the making of evidence-based recommendations on effective policies; comprehensive and value-added engagement with stakeholders; creating knowledge that is relevant and enhances the developmental impact of public resources, through mobilising a balance of internal and external specialist talent that is commensurate with the needs of the Commission; creating and nurturing a dynamic, productive organisational culture; and balancing present and future demands so that effective performance ensues within the constraints of available resources.',
			'current_tenders' => '',
			'vacancies' => '',
			'status' => '1',
			'status_reason' => '',
			'newsletter' => '1',
			'person_count' => '9',
			'annual_type_id' => '2',
			'created' => '0000-00-00 00:00:00',
			'modified' => '2015-04-24 14:06:09'
		),
		'UnitType' => array(
			'id' => '4',
			'name' => 'Constitutional Body',
			'menu_name' => 'Constitutional Bodies',
			'display' => '1',
			'sort_order' => '3',
			'created' => '2015-01-28 10:40:17',
			'modified' => '2015-04-07 12:07:37'
		),
		'children' => array()
	),
	array(
		'Unit' => array(
			'id' => '56',
			'unit_type_id' => '4',
			'name' => 'Land Claims Court (LCC)',
			'parent_id' => null,
			'lft' => '771',
			'rght' => '772',
			'province_id' => '1',
			'web_address' => 'www.justice.gov.za/lcc/',
			'physical_address' => 'Trust Bank Centre, Randburg Mall, Cnr Hill Street & Kent Avenue, Randburg, 2194',
			'postal_address' => 'Private Bag X10060, Randburg, 2125',
			'telephone' => '011 781 2291',
			'fax' => '011 781 2217/8',
			'email' => 'webmaster@justice.gov.za',
			'description' => 'The Land Claims Court was established in 1996 and its primary focus is dealing with land restitution / land claims cases. The court deals with restitution cases in the form of referrals from the commissiones office or when they come directly through claimants or affected land owners. The main task of the court in this regard is therefore to adjudicate whatever legal issues contained in the cases and ensure that land is awarded to those who satisfy the statutory requirements. The court also deals with the Extension of Security Tenure Act and the Labour Tenants Act. These two acts were enacted by parliament to protect farm dwellers/workers from ill treatment and illegal evictions. The Land Claims Court was conferred with the jurisdiction thereof. However the various magistrate courts around the country also have jurisdiction in terms of the Extension of Security Tenure Act although their orders pertaining evictions are subject to automatic reviews by this court. Primarily, the court has to ensure that the rights of farm workers/dwellers are protected in that all evictions are done within the framework of the aforementioned legislation. In carrying out its mandate the court therefore conducts hearings to adjudicate all matters related to the aforementioned legislation in various provinces, districts, cities and towns of the country.',
			'current_tenders' => '',
			'vacancies' => '',
			'status' => '1',
			'status_reason' => '',
			'newsletter' => '1',
			'person_count' => '7',
			'annual_type_id' => '3',
			'created' => '0000-00-00 00:00:00',
			'modified' => '2015-04-24 14:06:09'
		),
		'UnitType' => array(
			'id' => '4',
			'name' => 'Constitutional Body',
			'menu_name' => 'Constitutional Bodies',
			'display' => '1',
			'sort_order' => '3',
			'created' => '2015-01-28 10:40:17',
			'modified' => '2015-04-07 12:07:37'
		),
		'children' => array()
	),
	array(
		'Unit' => array(
			'id' => '10',
			'unit_type_id' => '3',
			'name' => 'Department: Cooperative Governance',
			'parent_id' => null,
			'lft' => '129',
			'rght' => '136',
			'province_id' => '1',
			'web_address' => 'www.cogta.gov.za',
			'physical_address' => '87 Hamilton Street, Arcadia, Pretoria',
			'postal_address' => 'Private Bag X804, Pretoria, 0001',
			'telephone' => '012 334 0600',
			'fax' => '012 334 0603',
			'email' => 'enquiry@cogta.gov.za',
			'description' => 'The mission of the Department of Cooperative Governance and Traditional Affairs is to facilitate cooperative governance and support all spheres of government, promote traditional affairs and support associated institutions through: developing appropriate policies and legislation to promote integration in governmens development programmes and service delivery; providing strategic interventions, support and partnerships to facilitate policy implementation in the provinces and local government; and creating enabling mechanisms for communities to participate in governance. The Departmens strategic goals are to: facilitate implementation of a policy that provides for a differentiated approach to municipal financing, planning and support; facilitate improved access to basic services and sustainable infrastructure; facilitate and implement the Community Work Programme at local level; deepen participatory democracy through a refined Ward Committee model; enhance administrative and financial capabilities of municipalities; strengthen cooperative governance and provide oversight and support to provincial and local government; strengthen the capacity of the department to deliver on its mandate; strengthen the effectiveness of cooperative governance through the development and roll-out of policies and legislation; facilitate implementation of sustainable economic development initiatives at local level; strengthen, coordinate and support effective integrated disaster management and fire services; and strengthen measures to fight corruption and unethical conduct.',
			'current_tenders' => '',
			'vacancies' => '',
			'status' => '1',
			'status_reason' => '',
			'newsletter' => '1',
			'person_count' => '18',
			'annual_type_id' => '1',
			'created' => '0000-00-00 00:00:00',
			'modified' => '2015-04-24 14:06:09'
		),
		'UnitType' => array(
			'id' => '3',
			'name' => 'National Department',
			'menu_name' => 'National Departments',
			'display' => '1',
			'sort_order' => '4',
			'created' => '2015-01-28 10:40:08',
			'modified' => '2015-04-07 12:07:37'
		),
		'children' => array(
			array(
				'Unit' => array(
					'id' => '57',
					'unit_type_id' => '4',
					'name' => 'Municipal Demarcation Board (MDB)',
					'parent_id' => '10',
					'lft' => '130',
					'rght' => '131',
					'province_id' => '1',
					'web_address' => 'www.demarcation.org.za',
					'physical_address' => 'Eco Origins Office Park, Block C1, 349 Witch Hazel Street, Highveld, 0157',
					'postal_address' => 'Private Bag X28, Hatfield, 0028',
					'telephone' => '012 342 2481/2',
					'fax' => '012 342 2480',
					'email' => 'info@demarcation.org.za',
					'description' => 'The mission of the Municipal Demarcation Board is to perform its functions and to exercise its powers in such a manner as to empower municipalities to fulfil their constitutional obligations, primarily the provision of democratic and accountable local government, and effective, efficient and sustainable service delivery within sound boundaries. The Board is an independent authority responsible for the determination of municipal boundaries. The Boars status as an independent authority is also protected by section 3 of The Local Government: Municipal Demarcation Act, 1998, and various judgements by the Constitutional Court. In addition to the determinations and re-determinations of municipal boundaries, the Board is also mandated by legislation to declare the district management areas; to delimit wards for local elections; and to assess the capacity of municipalities to perform their functions. The legislation provides for the following functions of the Board: determination and re-determination of municipal boundaries; delimitation of wards for local elections assessment of the capacity of district and local municipalities to perform their functions as provided for in the Constitution and the Structures Act; and the declaration and withdrawal of the declaration of district management areas. In addition, Cabinet approved a leading role for the Board in assisting Government Departments in aligning their functional service delivery boundaries to municipal boundaries.',
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '12',
					'annual_type_id' => '2',
					'created' => '0000-00-00 00:00:00',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '4',
					'name' => 'Constitutional Body',
					'menu_name' => 'Constitutional Bodies',
					'display' => '1',
					'sort_order' => '3',
					'created' => '2015-01-28 10:40:17',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			),
			array(
				'Unit' => array(
					'id' => '249',
					'unit_type_id' => '6',
					'name' => 'Municipal Infrastructure Support Agency',
					'parent_id' => '10',
					'lft' => '132',
					'rght' => '133',
					'province_id' => '1',
					'web_address' => '',
					'physical_address' => '1303 Heuwel Avenue,  Riverside Office Park, Letaba House,  Centurion',
					'postal_address' => 'Private Bag X105, Centurion, 0046',
					'telephone' => '012 848 5300',
					'fax' => '',
					'email' => 'Communications@misa.gov.za',
					'description' => null,
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '0',
					'annual_type_id' => '3',
					'created' => '2015-02-23 15:19:54',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '6',
					'name' => 'Public Entity',
					'menu_name' => 'Public Entities',
					'display' => '1',
					'sort_order' => '6',
					'created' => '2015-01-28 10:40:34',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			),
			array(
				'Unit' => array(
					'id' => '171',
					'unit_type_id' => '6',
					'name' => 'South African Local Government Association (SALGA)',
					'parent_id' => '10',
					'lft' => '134',
					'rght' => '135',
					'province_id' => '1',
					'web_address' => 'www.salga.net',
					'physical_address' => 'Menlyn Corporate Park, Block B, 175 Corobay Avenue, Cnr Garsfontein & Corobay, Waterkloof Glen, Pretoria',
					'postal_address' => 'PO Box 2094, Pretoria, 0001',
					'telephone' => '012 369 8000',
					'fax' => '012 369 8001',
					'email' => 'info@salga.org.za',
					'description' => 'The mandate of the South African Local Government Association (SALGA) is to be the voice and sole representative of local government. SALGA interfaces with parliament, the National Council of Provinces (NCOP), Cabinet, as well as provincial legislatures. In line with its mandate SALGA has set out its role to: represent, promote and protect the interests of local government; transform local government to enable it to fulfill its developmental role; raise the profile of local government; ensure full participation of women in local government; perform its role as an employer body; and develop capacity within municipalities.',
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '2',
					'annual_type_id' => '2',
					'created' => '0000-00-00 00:00:00',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '6',
					'name' => 'Public Entity',
					'menu_name' => 'Public Entities',
					'display' => '1',
					'sort_order' => '6',
					'created' => '2015-01-28 10:40:34',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			)
		)
	),
	array(
		'Unit' => array(
			'id' => '18',
			'unit_type_id' => '3',
			'name' => 'Department: Home Affairs',
			'parent_id' => null,
			'lft' => '407',
			'rght' => '416',
			'province_id' => '1',
			'web_address' => 'www.dha.gov.za',
			'physical_address' => 'Hallmark Building, 230 Johannes Ramokhoase Street, Pretoria',
			'postal_address' => 'Private Bag X114, Pretoria, 0001',
			'telephone' => '012 406 2500 / 0800 60 11 90',
			'fax' => '086 512 7864',
			'email' => 'communications@dha.gov.za',
			'description' => 'The mission of the Department of Home Affairs is the efficient determination and safeguarding of the identity and status of citizens and the regulation of immigration to ensure security, promote development and fulfil our international obligations. The Departmens strategic outcome-orientated goals are to: establish a Border Management Agency and build a comprehensive, secure National Identity System, which will contribute significantly to reducing fraud and preventing identity theft; facilitate the importation of skills that are critical to ensuring economic growth and the creation of jobs; and providing an efficient, effective and development-orientated public service by being the custodian of the identity and status of citizens.',
			'current_tenders' => '',
			'vacancies' => '',
			'status' => '1',
			'status_reason' => '',
			'newsletter' => '1',
			'person_count' => '14',
			'annual_type_id' => '1',
			'created' => '0000-00-00 00:00:00',
			'modified' => '2015-04-24 14:06:09'
		),
		'UnitType' => array(
			'id' => '3',
			'name' => 'National Department',
			'menu_name' => 'National Departments',
			'display' => '1',
			'sort_order' => '4',
			'created' => '2015-01-28 10:40:08',
			'modified' => '2015-04-07 12:07:37'
		),
		'children' => array(
			array(
				'Unit' => array(
					'id' => '55',
					'unit_type_id' => '4',
					'name' => 'Independent Electoral Commission (IEC)',
					'parent_id' => '18',
					'lft' => '412',
					'rght' => '413',
					'province_id' => '1',
					'web_address' => 'www.elections.org.za',
					'physical_address' => 'Election House, Riverside Office Park, 1303 Heuwel Avenue, Centurion, Pretoria',
					'postal_address' => 'Private Bag X112, Centurion, 0046',
					'telephone' => '012 622 5700',
					'fax' => '012 622 5784',
					'email' => 'webmaster@elections.org.za',
					'description' => 'The mission of the Electoral Commission (IEC) is to be an independent constitutional body which manages free and fair elections of legislative bodies and institutions through the participation of citizens, political parties and civil society in deepening electoral democracy. The IEs obligations are to: manage elections of national, provincial and municipal legislative bodies; ensure that those elections are free and fair; declare the results of those elections; and compile and maintain a voters roll. The Commissios duties are to: compile and maintain a register of parties; undertake and promote research into electoral matters; develop and promote the development of electoral expertise and technology in all spheres of government; continuously review electoral laws and proposed electoral laws, and make recommendations; promote voter education; declare the results of elections for national, provincial and municipal legislative bodies within seven days; and appoint appropriate public administrations in any sphere of government to conduct elections when necessary.',
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '10',
					'annual_type_id' => '2',
					'created' => '0000-00-00 00:00:00',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '4',
					'name' => 'Constitutional Body',
					'menu_name' => 'Constitutional Bodies',
					'display' => '1',
					'sort_order' => '3',
					'created' => '2015-01-28 10:40:17',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			),
			array(
				'Unit' => array(
					'id' => '97',
					'unit_type_id' => '6',
					'name' => 'Film and Publication Board (FPB)',
					'parent_id' => '18',
					'lft' => '408',
					'rght' => '409',
					'province_id' => '1',
					'web_address' => 'www.fpb.org.za',
					'physical_address' => 'Eco Glade 2, 420 Witch Hazel Street, Eco Park, Centurion, 0169',
					'postal_address' => 'Private Bag X31, Highveld Park, 0169',
					'telephone' => '012 003 1400',
					'fax' => '',
					'email' => 'clientsupport@fpb.org.za',
					'description' => 'The mission of the Film and Publication Board (FPB) is to ensure efficient and effective consumer protection through regulation of media content, while empowering the public, especially children, through robust information sharing. The Board regulates the media environment through the classification of content by: maintaining relevance to the values and norms of South African society through scientific research; balancing the right to freedom of expression with an obligation to protect children from exposure to potentially disturbing, harmful and inappropriate materials; and protecting children from sexual exploitation in media content in order to educate the broader South African society to make informed choices.',
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '22',
					'annual_type_id' => '2',
					'created' => '0000-00-00 00:00:00',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '6',
					'name' => 'Public Entity',
					'menu_name' => 'Public Entities',
					'display' => '1',
					'sort_order' => '6',
					'created' => '2015-01-28 10:40:34',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			),
			array(
				'Unit' => array(
					'id' => '104',
					'unit_type_id' => '6',
					'name' => 'Government Printing Works (GPW)',
					'parent_id' => '18',
					'lft' => '410',
					'rght' => '411',
					'province_id' => '1',
					'web_address' => 'www.gpwonline.co.za/Pages/default.aspx',
					'physical_address' => '149 Bosman Street, Pretoria',
					'postal_address' => 'Private Bag X85, Pretoria, 0001',
					'telephone' => '012 748 6001/2',
					'fax' => '012 323 0009',
					'email' => 'info@gpw.gov.za',
					'description' => 'The mission of the Government Printing Works (GPW) is to: provide cost effective, reliable and timeous services to all spheres of government in printing; deliver equitable information to the public; and disseminate government information through technology, innovation and service excellence. Utilising the latest technologies, the GPW is fully equipped to focus on its customers communication needs, delivering a comprehensive suite of printing, security printing, publishing and dissemination services to both the South African government and the public. As the custodian and publisher of Government Gazettes,  the official publications used by government to communicate messages of national importance to the general public,  the GPW now also provides its customers with convenient electronic access to submit content, read current gazettes and access all back issues. To further enhance its service offering, the GPW has created an end-to-end consulting service for clients wanting to do business with the organisation. As stated by the National Treasury, government departments wanting to make use of the GPs services need not go out to tender first.',
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '7',
					'annual_type_id' => '2',
					'created' => '0000-00-00 00:00:00',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '6',
					'name' => 'Public Entity',
					'menu_name' => 'Public Entities',
					'display' => '1',
					'sort_order' => '6',
					'created' => '2015-01-28 10:40:34',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			),
			array(
				'Unit' => array(
					'id' => '151',
					'unit_type_id' => '6',
					'name' => 'Refugee Appeal Board',
					'parent_id' => '18',
					'lft' => '414',
					'rght' => '415',
					'province_id' => '1',
					'web_address' => '',
					'physical_address' => 'Sanlam Middlestad Building, 16Th Floor, 252 Cnr Pretorius And Andries Streets, Pretoria',
					'postal_address' => 'Private Bag X500, Pretoria, 0001',
					'telephone' => '012 320 1191',
					'fax' => '012 320 1297',
					'email' => '',
					'description' => null,
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '2',
					'annual_type_id' => '3',
					'created' => '0000-00-00 00:00:00',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '6',
					'name' => 'Public Entity',
					'menu_name' => 'Public Entities',
					'display' => '1',
					'sort_order' => '6',
					'created' => '2015-01-28 10:40:34',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			)
		)
	),
	array(
		'Unit' => array(
			'id' => '21',
			'unit_type_id' => '3',
			'name' => 'Department: International Relations and Cooperation',
			'parent_id' => null,
			'lft' => '443',
			'rght' => '446',
			'province_id' => '1',
			'web_address' => 'www.dirco.gov.za',
			'physical_address' => 'OR Tambo Building, 460 Soutpansberg Road, Rietondale, Pretoria, 0084',
			'postal_address' => 'Private Bag X152, Pretoria, 0001',
			'telephone' => '012 351 1000',
			'fax' => '012 329 1000',
			'email' => 'webmaster@dirco.gov.za',
			'description' => 'The mission of the Department of International Relations and Cooperation is to promote South Africs national interests and values, the African Renaissance and the creation of a better world for all. The Departmens strategic objectives are to: protect and promote South African National interests and values through bilateral and multilateral interactions; conduct and coordinate South Africs international relations and promote its foreign policy objectives; monitor international developments and advise government on foreign policy and related domestic matters; protect South Africs sovereignty and territorial integrity; contribute to the formulation of international law and enhance respect for the provisions thereof; promote multilateralism to secure a rules based international system; maintain a modern, effective and excellence driven department; provide consular services to South African nationals abroad; and provide a world-class and uniquely South African State Protocol service.',
			'current_tenders' => '',
			'vacancies' => '',
			'status' => '1',
			'status_reason' => '',
			'newsletter' => '1',
			'person_count' => '24',
			'annual_type_id' => '1',
			'created' => '0000-00-00 00:00:00',
			'modified' => '2015-04-24 14:06:09'
		),
		'UnitType' => array(
			'id' => '3',
			'name' => 'National Department',
			'menu_name' => 'National Departments',
			'display' => '1',
			'sort_order' => '4',
			'created' => '2015-01-28 10:40:08',
			'modified' => '2015-04-07 12:07:37'
		),
		'children' => array(
			array(
				'Unit' => array(
					'id' => '197',
					'unit_type_id' => '6',
					'name' => 'African Renaissance International Cooperation',
					'parent_id' => '21',
					'lft' => '444',
					'rght' => '445',
					'province_id' => '1',
					'web_address' => 'www.dfa.gov.za/foreign/Multilateral/profiles/arfund.htm',
					'physical_address' => '',
					'postal_address' => '',
					'telephone' => '',
					'fax' => '',
					'email' => '',
					'description' => null,
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '0',
					'annual_type_id' => '3',
					'created' => '2015-02-20 10:31:29',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '6',
					'name' => 'Public Entity',
					'menu_name' => 'Public Entities',
					'display' => '1',
					'sort_order' => '6',
					'created' => '2015-01-28 10:40:34',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			)
		)
	),
	array(
		'Unit' => array(
			'id' => '34',
			'unit_type_id' => '3',
			'name' => 'Department: Public Works',
			'parent_id' => null,
			'lft' => '577',
			'rght' => '588',
			'province_id' => '1',
			'web_address' => 'www.publicworks.gov.za',
			'physical_address' => '256 Madiba Street, Pretoria',
			'postal_address' => 'Private Bag X65, Pretoria, 0001',
			'telephone' => '012 406 1000',
			'fax' => '086 272 8986',
			'email' => 'dg.pa@dpw.gov.za',
			'description' => 'The mission of the Department of Public Works is to promote the governmens objectives of economic development, good governance and rising living standards and prosperity by providing and managing the accommodation, infrastructure needs of national departments, by leading the national Expanded Public Works Programme and transformation of the construction and property industries. In pursuance of this objective the Department will endeavour to: efficiently manage the asset life cycle of immovable assets under the Departmens custodianship; provide expert advice to all three spheres of government and parastatals on immovable assets; contribute to the national goals of job creation and poverty alleviation through programme management, leading and directing of public works programmes nationally, of which the Expanded Public Works Programme forms an integral part; and provides strategic leadership to the construction and property industries.',
			'current_tenders' => '',
			'vacancies' => '',
			'status' => '1',
			'status_reason' => '',
			'newsletter' => '1',
			'person_count' => '21',
			'annual_type_id' => '1',
			'created' => '0000-00-00 00:00:00',
			'modified' => '2015-04-24 14:06:09'
		),
		'UnitType' => array(
			'id' => '3',
			'name' => 'National Department',
			'menu_name' => 'National Departments',
			'display' => '1',
			'sort_order' => '4',
			'created' => '2015-01-28 10:40:08',
			'modified' => '2015-04-07 12:07:37'
		),
		'children' => array(
			array(
				'Unit' => array(
					'id' => '210',
					'unit_type_id' => '6',
					'name' => 'Construction Industry Development Board (CIDB)',
					'parent_id' => '34',
					'lft' => '578',
					'rght' => '579',
					'province_id' => '1',
					'web_address' => 'www.cidb.org.za',
					'physical_address' => 'Block N&R, SABS Campus, 2 Dr Lategan Road, Groenkloof, Pretoria',
					'postal_address' => 'PO Box 2107, Brooklyn Square, 0075',
					'telephone' => '012 482 7200 ',
					'fax' => '012 349 8986',
					'email' => 'cidb@cidb.org.za',
					'description' => 'The mission of the Construction Industry Development Board (CIDB) is to direct and drive an integrated construction industry development strategy that transforms the role of industry and stakeholders for sustainable growth, improved delivery, performance and value to public and private sector clients, and investors through strategic partnerships; to strategically and deliberately promote the empowerment of small, medium and micro enterprises to improve their capability and grow the economy; to develop employees to be meaningful participants in the organization. The Boars mandate is to: establish a national register of contractors and of construction projects to systematically regulate, monitor and promote the performance of the industry for sustainable growth, delivery and empowerment; promote improved delivery management capacity and the uniform application of procurement policy throughout all spheres of government; promote improved performance and best practice of public and private sector clients, contractors and other participants in the construction delivery process; promote sustainable participation of the emerging sector; and provide strategic direction and develop effective partnerships for growth, reform and improvement of the construction sector.',
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '18',
					'annual_type_id' => '2',
					'created' => '2015-02-23 09:03:01',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '6',
					'name' => 'Public Entity',
					'menu_name' => 'Public Entities',
					'display' => '1',
					'sort_order' => '6',
					'created' => '2015-01-28 10:40:34',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			),
			array(
				'Unit' => array(
					'id' => '213',
					'unit_type_id' => '6',
					'name' => 'Council for the Built Environment (CBE)',
					'parent_id' => '34',
					'lft' => '580',
					'rght' => '581',
					'province_id' => '1',
					'web_address' => 'www.cbe.org.za',
					'physical_address' => '121 Muckleneuk (Cnr Middel & Florence Ribeiro Avenues), Nieuw Muckleneuk, Brooklyn, Pretoria',
					'postal_address' => 'PO Box 915, Groenkloof, 0027',
					'telephone' => '012 346 3985',
					'fax' => '012 346 3986',
					'email' => 'info@cbe.org.za',
					'description' => 'The mission of the Council for the Built Environment (CBE) is to implement projects and programmes that address built environment issues and add value to the built environment professions, government and the general public. The CBs mandate is to: promote and protect the interests of the public in the built environment; promote and maintain a sustainable built environment and natural environment; promote ongoing human resource development in the built environment; facilitate participation by the built environment professions in integrated development in the context of national goals; promote appropriate standards of health, safety and environmental protection within the built environment; promote sound governance of the built environment professions; promote liaison in the field of training in South Africa and elsewhere, and to promote the standards of such training in the country; serve as a forum where the built environment professions can discuss relevant issues; and ensure uniform application of norms and guidelines set by the Professional Councils throughout the built environment.',
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '28',
					'annual_type_id' => '2',
					'created' => '2015-02-23 10:14:03',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '6',
					'name' => 'Public Entity',
					'menu_name' => 'Public Entities',
					'display' => '1',
					'sort_order' => '6',
					'created' => '2015-01-28 10:40:34',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			),
			array(
				'Unit' => array(
					'id' => '108',
					'unit_type_id' => '6',
					'name' => 'Independent Development Trust (IDT)',
					'parent_id' => '34',
					'lft' => '582',
					'rght' => '583',
					'province_id' => '1',
					'web_address' => 'www.idt.org.za',
					'physical_address' => 'Glenwood Office Park, Cnr Oberon & Sprite Streets, Faerie Glen, Pretoria',
					'postal_address' => 'PO Box 73000, Lynnwood Ridge, 0043',
					'telephone' => '012 845 2000',
					'fax' => '012 348 0894',
					'email' => 'info@idt.org.za',
					'description' => 'The mission of the Independent Development Trust (IDT) is to manage and deliver integrated social infrastructure programmes on behalf of government on time, cost effectively and through a people centred approach. The IDT undertakes development programme management on behalf of government. The programmes cut across a number of sectors, but are largely within the social infrastructure domain. The IDT works with all spheres of government, i.e. national, provincial and local government. The development agencs portfolio is broadly categorized into social infrastructure programmes and social development programmes. Social infrastructure programmes entail the provision and maintenance of infrastructure facilities that enable government to deliver social, basic and community services to its citizens. Social infrastructure projects include schools, Early Childhood Development Centres (ECDC), clinics, hospitals, courts, community halls, portable water and sanitation infrastructure, etc. Social development programmes on the other hand, entail initiatives and development interventions that primarily facilitate job creation, poverty eradication, community enterprise support and community empowerment. Social development programmes include initiatives like Expanded Public Works Programme (EPWP), Working for Water Alien Vegetation Removal Programme, Food for Waste Programme, Comprehensive Rural Development Programme etc.',
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '15',
					'annual_type_id' => '2',
					'created' => '0000-00-00 00:00:00',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '6',
					'name' => 'Public Entity',
					'menu_name' => 'Public Entities',
					'display' => '1',
					'sort_order' => '6',
					'created' => '2015-01-28 10:40:34',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			),
			array(
				'Unit' => array(
					'id' => '386',
					'unit_type_id' => '6',
					'name' => 'Parliamentary Villages Management Board',
					'parent_id' => '34',
					'lft' => '584',
					'rght' => '585',
					'province_id' => '1',
					'web_address' => '',
					'physical_address' => '',
					'postal_address' => '',
					'telephone' => '',
					'fax' => '',
					'email' => '',
					'description' => null,
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '0',
					'annual_type_id' => '3',
					'created' => '2015-03-02 16:01:17',
					'modified' => '2015-04-24 14:06:10'
				),
				'UnitType' => array(
					'id' => '6',
					'name' => 'Public Entity',
					'menu_name' => 'Public Entities',
					'display' => '1',
					'sort_order' => '6',
					'created' => '2015-01-28 10:40:34',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			),
			array(
				'Unit' => array(
					'id' => '280',
					'unit_type_id' => '6',
					'name' => 'Property Management Trading Entity',
					'parent_id' => '34',
					'lft' => '586',
					'rght' => '587',
					'province_id' => '1',
					'web_address' => '',
					'physical_address' => '',
					'postal_address' => '',
					'telephone' => '',
					'fax' => '',
					'email' => '',
					'description' => null,
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '0',
					'annual_type_id' => '3',
					'created' => '2015-02-25 09:45:59',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '6',
					'name' => 'Public Entity',
					'menu_name' => 'Public Entities',
					'display' => '1',
					'sort_order' => '6',
					'created' => '2015-01-28 10:40:34',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			)
		)
	),
	array(
		'Unit' => array(
			'id' => '47',
			'unit_type_id' => '3',
			'name' => 'Department: Traditional Affairs',
			'parent_id' => null,
			'lft' => '695',
			'rght' => '698',
			'province_id' => '1',
			'web_address' => 'www.dta.gov.za',
			'physical_address' => '1 Pencadia Building, 509 Pretorius Street, Pretoria',
			'postal_address' => 'Private Bag X804, Pretoria, 0001',
			'telephone' => '012 336 5824/25',
			'fax' => '012 336 5952',
			'email' => '',
			'description' => 'The mission of the Department of Traditional Affairs is to coordinate traditional affairs activities across government through: development of appropriate policies, norms and standards, systems and regulatory framework governing traditional affairs; provision of support to traditional affairs institution; enhancement of information and knowledge management on traditional affairs; and promotion of culture, heritage and social cohesion.',
			'current_tenders' => '',
			'vacancies' => '',
			'status' => '1',
			'status_reason' => '',
			'newsletter' => '1',
			'person_count' => '12',
			'annual_type_id' => '1',
			'created' => '0000-00-00 00:00:00',
			'modified' => '2015-04-24 14:06:09'
		),
		'UnitType' => array(
			'id' => '3',
			'name' => 'National Department',
			'menu_name' => 'National Departments',
			'display' => '1',
			'sort_order' => '4',
			'created' => '2015-01-28 10:40:08',
			'modified' => '2015-04-07 12:07:37'
		),
		'children' => array(
			array(
				'Unit' => array(
					'id' => '51',
					'unit_type_id' => '4',
					'name' => 'Commission for the Promotion and Protection of the Rights of Cultural, Religious and Linguistic Communities',
					'parent_id' => '47',
					'lft' => '696',
					'rght' => '697',
					'province_id' => '1',
					'web_address' => 'www.crlcommission.org.za',
					'physical_address' => 'West Wing, 1st Floor, 158 Jan Smuts Avenue, Rosebank, Johannesburg',
					'postal_address' => 'Private Bag X90 000, Houghton, 2041',
					'telephone' => '011 358 9100',
					'fax' => '011 403 2098',
					'email' => 'info@crlcommission.org.za',
					'description' => 'The Commission for the Promotion and Protection of the Rights of Cultural, Religious and Linguistic Communities is responsible for deepening the appreciation of South Africans for the wide array of cultures, religions and languages found in our country and for contributing meaningfully and constructively to social transformation and nation building for the attainment of a truly united South African nation. The Commission was established to fulfil the following objectives: promote and develop peace, friendship, humanity, tolerance and national unity among and within cultural, religious and linguistic communities on the basis of equity, non-discrimination and free association; foster mutual respect among cultural, religious and linguistic communities; promote the right of communities to develop their historically diminished heritage; promote respect for and further the protection of the rights of cultural, religious and linguistic communities; and recommend the establishment or recognition of community councils in accordance with Section 36 or 37.',
					'current_tenders' => '',
					'vacancies' => '',
					'status' => '1',
					'status_reason' => '',
					'newsletter' => '1',
					'person_count' => '19',
					'annual_type_id' => '2',
					'created' => '0000-00-00 00:00:00',
					'modified' => '2015-04-24 14:06:09'
				),
				'UnitType' => array(
					'id' => '4',
					'name' => 'Constitutional Body',
					'menu_name' => 'Constitutional Bodies',
					'display' => '1',
					'sort_order' => '3',
					'created' => '2015-01-28 10:40:17',
					'modified' => '2015-04-07 12:07:37'
				),
				'children' => array()
			)
		)
	)
)

?>